spring:
  config:
      import: optional:file:.env[.properties]
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_SCHEMA}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
impulso:
  codigoIBGE: ${CODIGO_IBGE}